[package]
name = "video-chat"
version = "0.1.0"
authors = ["Eugene Zemtsov <eugene@chromium.org>"]
edition = "2018"

[dependencies]
actix = "0.10"
actix-broker = "*"
actix-files = "*"
actix-rt = "*"
actix-web = "3"
actix-web-actors = "3"
env_logger = "*"
futures = "*"
log = "*"
rand = "*"

